# Generated by Django 3.2.13 on 2022-06-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djflights', '0002_auto_20220604_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='djflights.Flight')),
            ],
        ),
    ]
