# Generated by Django 3.2.13 on 2022-06-05 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djflights', '0004_package_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
        migrations.RemoveField(
            model_name='package',
            name='slug',
        ),
    ]
