# Generated by Django 3.2.13 on 2022-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djflights', '0005_auto_20220605_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service'),
        ),
    ]
