# Generated by Django 3.2.13 on 2022-06-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djflights', '0007_alter_package_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
